//
// Created by nikita on 10.10.17.
//

#ifndef VALIDATIONTASK_HASH_COUNTING_H
#define VALIDATIONTASK_HASH_COUNTING_H

#define HASH_MD5	0xCC0000D5
#define HASH_CRC32	0xCC000C32



#endif //VALIDATIONTASK_HASH_COUNTING_H
